add CD

diff --git a/jenkins/Jenkinsfile b/jenkins/Jenkinsfile
--- a/jenkins/Jenkinsfile
+++ b/jenkins/Jenkinsfile
@@ -21,6 +21,51 @@ node {
             sh 'npm run ci:jenkins-test'
         }
     }
+
+    stage('Manual Approval') {
+        input message: 'Lanjutkan ke tahap Deploy?'
+    }
+
+    stage('Deploy') {
+        def serverUser = "ubuntu"
+        def serverIP = "ec2-13-215-194-192.ap-southeast-1.compute.amazonaws.com"
+        def deployDir = "/home/${serverUser}/discussion-app"
+        
+        withCredentials([file(credentialsId: 'my-server', variable: 'secretFile')]) { 
+            sh """
+                scp -i ${secretFile} -r .next ${serverUser}@${serverIP}:${deployDir}/.next
+                scp -i ${secretFile} package.json ${serverUser}@${serverIP}:${deployDir}
+                scp -i ${secretFile} package-lock.json ${serverUser}@${serverIP}:${deployDir}
+                scp -i ${secretFile} Dockerfile ${serverUser}@${serverIP}:${deployDir}
+
+                ssh -i ${secretFile} ${serverUser}@${serverIP} "
+                    if ! command -v docker &> /dev/null; then
+                        echo 'Docker not found. Installing Docker...'
+                        sudo apt update
+                        sudo apt install -y docker.io
+                        sudo systemctl enable --now docker
+                    else
+                        echo 'Docker is already installed.'
+                    fi
+                "
+
+                ssh -i ${secretFile} ${serverUser}@${serverIP} "
+                    cd ${deployDir} && 
+                    docker rm -f discussion-app || true &&
+                    docker build -t discussion-app . &&
+                    docker run -d \
+                        --name discussion-app \
+                        --restart on-failure \
+                        -p 3000:3000 \
+                        -e NEXT_PUBLIC_BASE_API=${env.NEXT_PUBLIC_BASE_API} \
+                        -e NEXTAUTH_SECRET=${env.NEXTAUTH_SECRET} \
+                        -e NEXTAUTH_URL=${env.NEXTAUTH_URL} \
+                        discussion-app
+                "
+            """
+        }
+        sh 'sleep 60'
+    }
 }
 
 /* 
@@ -29,9 +74,9 @@ pipeline {
     agent any
 
     environment {
-        NEXT_PUBLIC_BASE_API = 'https://forum-api.dicoding.dev/v1'
-        NEXTAUTH_SECRET = 'hMzxv6I31UnuslbQ7aQsooLWw0rVzD+X9Z445egm/68='
-        NEXTAUTH_URL = 'http://localhost:3000/api/auth'
+        NEXT_PUBLIC_BASE_API = ''
+        NEXTAUTH_SECRET = ''
+        NEXTAUTH_URL = ''
     }
 
     stages {
